/* ─────────────────────────────────────────────────────────────────────
   TOOOL — grid → pieces

   Takes ONE prepared "spectrum" grid image (a single horizontal row of N
   objects on a white background — made in Figma or generated by ChatGPT) and
   slices it into N clean pieces the result window can show. The slice is a
   plain equal-column split (deterministic — always works), and each piece is
   then trimmed to the object's bounding box so it comes out large + centred no
   matter exactly where it sat in its cell.

   Exposes: window.loadGridImage(source, n) → Promise<string[]>  (N data-URLs)
   ───────────────────────────────────────────────────────────────────── */

(() => {
  function loadImage(src) {
    return new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = reject;
      img.src = src;
    });
  }

  /* copy a sub-rect of an image/canvas into a fresh canvas */
  function crop(src, sx, sy, sw, sh) {
    const c = document.createElement('canvas');
    c.width = sw;
    c.height = sh;
    c.getContext('2d').drawImage(src, sx, sy, sw, sh, 0, 0, sw, sh);
    return c;
  }

  /* split the source into n equal-width columns */
  function sliceColumns(img, n) {
    const w = img.naturalWidth || img.width;
    const h = img.naturalHeight || img.height;
    const cw = w / n;
    const cells = [];
    for (let i = 0; i < n; i++) {
      const x = Math.round(i * cw);
      const nextX = Math.round((i + 1) * cw);
      cells.push(crop(img, x, 0, nextX - x, h));
    }
    return cells;
  }

  /* make the background transparent: flood-fill inward from every border pixel,
     clearing pixels that match the corner colour. Because it only spreads from
     the edges it removes the surrounding background WITHOUT punching holes in
     white areas inside the object (a light handle, a highlight, …). */
  function removeBackground(canvas, tol = 50) {
    const w = canvas.width;
    const h = canvas.height;
    const ctx = canvas.getContext('2d');
    const imgData = ctx.getImageData(0, 0, w, h);
    const d = imgData.data;
    const bg = [d[0], d[1], d[2]];
    const isBg = (o) => Math.abs(d[o] - bg[0]) + Math.abs(d[o + 1] - bg[1]) + Math.abs(d[o + 2] - bg[2]) <= tol;

    const visited = new Uint8Array(w * h);
    const stack = [];
    for (let x = 0; x < w; x++) { stack.push(x, (h - 1) * w + x); }        // top + bottom edges
    for (let y = 0; y < h; y++) { stack.push(y * w, y * w + (w - 1)); }    // left + right edges

    while (stack.length) {
      const p = stack.pop();
      if (visited[p]) continue;
      visited[p] = 1;
      const o = p * 4;
      if (!isBg(o)) continue;          // hit the object edge → stop spreading here
      d[o + 3] = 0;                    // clear the background pixel
      const x = p % w, y = (p - x) / w;
      if (x > 0)     stack.push(p - 1);
      if (x < w - 1) stack.push(p + 1);
      if (y > 0)     stack.push(p - w);
      if (y < h - 1) stack.push(p + w);
    }
    ctx.putImageData(imgData, 0, 0);
    return canvas;
  }

  /* crop a cell down to its object (drop the surrounding background) so the
     object fills the frame; background is sampled from the corners */
  function trimToObject(canvas, padFrac = 0.06) {
    const w = canvas.width;
    const h = canvas.height;
    const data = canvas.getContext('2d').getImageData(0, 0, w, h).data;

    const px = (x, y) => (y * w + x) * 4;
    const bg = [data[0], data[1], data[2], data[3]];   // top-left corner = background
    const isObject = (o) => {
      if (data[o + 3] < 240) return true;              // transparent-ish → not background
      return Math.abs(data[o] - bg[0]) +
             Math.abs(data[o + 1] - bg[1]) +
             Math.abs(data[o + 2] - bg[2]) > 40;       // clearly different colour → object
    };

    let minX = w, minY = h, maxX = -1, maxY = -1;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        if (isObject(px(x, y))) {
          if (x < minX) minX = x;
          if (x > maxX) maxX = x;
          if (y < minY) minY = y;
          if (y > maxY) maxY = y;
        }
      }
    }
    if (maxX < 0) return canvas;                        // empty cell — leave as-is

    const objW = maxX - minX + 1;
    const objH = maxY - minY + 1;
    const pad = Math.round(Math.max(objW, objH) * padFrac);
    minX = Math.max(0, minX - pad);
    minY = Math.max(0, minY - pad);
    maxX = Math.min(w - 1, maxX + pad);
    maxY = Math.min(h - 1, maxY + pad);
    return crop(canvas, minX, minY, maxX - minX + 1, maxY - minY + 1);
  }

  /* main entry: slice + trim → array of N PNG data-URLs.
     `source` may be a URL/data-URL string, or a File/Blob. */
  async function loadGridImage(source, n = 5) {
    let src = source;
    let revoke = null;
    if (source instanceof Blob) { src = URL.createObjectURL(source); revoke = src; }
    try {
      const img = await loadImage(src);
      return sliceColumns(img, n)
        .map(cell => trimToObject(removeBackground(cell)).toDataURL('image/png'));
    } finally {
      if (revoke) URL.revokeObjectURL(revoke);
    }
  }

  window.loadGridImage = loadGridImage;
})();
